name: hola-mundo
on: [push]
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Run main
        run: python main.py
